services:
  mysql:
    image: mysql:9.2
    container_name: mysql-dieta
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dieta
      MYSQL_USER: dieta
      MYSQL_PASSWORD: dieta
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./mysql_tmp:/tmp
    ports:
      - "3306:3306"

