server:
  port: 8082
  address: 0.0.0.0

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dieta
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: dieta-anabolica-backend
            client-secret: kFnxQ2FmRTnpuAjY3Rru5XHUFIBZebL8
            scope: openid
            authorization-grant-type: password
        provider:
          keycloak:
            issuer-uri: http://localhost:8081/realms/dieta-anabolica

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
